version: "3.8"
services:
  db:
    image: postgres:15.5
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql
  mail:
    image: dockage/mailcatcher:0.9.0
    ports:
      - 1025:1025
      - 1080:1080
  server:
    build: .
    command: bash -l -c "npm install && npm start"
    environment:
      - FASTIFY_PORT=5100
      - FASTIFY_ADDRESS=0.0.0.0
    ports:
      - 5000:5000 #fastify
      - 5100:5100 #vite
    depends_on:
      - db
      - mail
    volumes:
      - .:/opt/node/app
      - /opt/node/app/node_modules
      - /opt/node/app/client/node_modules
      - /opt/node/app/server/node_modules
